# Generated by Django 2.2 on 2020-01-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='isSecurity',
        ),
        migrations.AddField(
            model_name='person',
            name='designation',
            field=models.IntegerField(choices=[(1, 'Employee'), (2, 'Security'), (3, 'Admin')], default=1),
        ),
    ]
