# Generated by Django 2.2.7 on 2020-01-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200107_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='isPresent',
            field=models.BooleanField(default='True'),
        ),
    ]
