# Generated by Django 2.2 on 2020-01-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(default='/home/anuraag/sih/sih/photos/default.jpg', upload_to=''),
        ),
    ]
